// Package workloads provides the coordinator-side view of the SDK workload
// library. The catalog is generated by `scimesh workload export` and embedded
// into the binary; it is presentation and orchestration metadata, never
// executable code. Every field that drives coordinator behaviour (reduction
// mode, parameter schema, required input columns) is validated at load time
// so a bad export fails fast instead of misbehaving at runtime.
package workloads

import (
	"embed"
	"encoding/json"
	"fmt"
	"sort"
)

//go:embed workloads.json
var catalogFile embed.FS

// Catalog is the parsed and validated workload library.
type Catalog struct {
	workloads []*Workload
}

// Workload is one entry of the embedded catalog.
type Workload struct {
	Name              string            `json:"name"`
	Version           string            `json:"version"`
	Description       string            `json:"description"`
	Capabilities      []string          `json:"capabilities"`
	TrustModes        []string          `json:"trust_modes"`
	Determinism       string            `json:"determinism"`
	Verifier          string            `json:"verifier"`
	Enabled           bool              `json:"enabled"`
	Reduction         string            `json:"reduction"`
	UploadReady       bool              `json:"upload_ready"`
	Parameters        map[string]any    `json:"parameters_schema"`
	UIElements        []UIElement       `json:"ui_elements"`
	Inputs            map[string]any    `json:"inputs"`
	Outputs           map[string]any    `json:"outputs"`
	requiredColumns   map[string]bool   // derived from input validator configuration
	inputMediaTypes   map[string]string // port name -> media type
	parameterDefaults map[string]any    // derived from the schema
}

// UIElement is one workload-declared form control for the "new job" page.
type UIElement struct {
	Field       string   `json:"field"`
	Widget      string   `json:"widget"`
	Label       string   `json:"label"`
	Help        string   `json:"help"`
	Placeholder string   `json:"placeholder"`
	Options     []string `json:"options"`
	Default     any      `json:"default"`
	Order       int      `json:"order"`
	Group       string   `json:"group"`
}

type libraryFile struct {
	SchemaVersion int         `json:"schema_version"`
	GeneratedBy   string      `json:"generated_by"`
	Workloads     []*Workload `json:"workloads"`
}

// Load reads and validates the embedded catalog.
func Load() (*Catalog, error) {
	raw, err := catalogFile.ReadFile("workloads.json")
	if err != nil {
		return nil, fmt.Errorf("read embedded workload catalog: %w", err)
	}
	return Parse(raw)
}

// Parse validates and builds a Catalog from catalog JSON bytes.
func Parse(raw []byte) (*Catalog, error) {
	var file libraryFile
	if err := json.Unmarshal(raw, &file); err != nil {
		return nil, fmt.Errorf("parse workload catalog: %w", err)
	}
	if file.SchemaVersion != 2 {
		return nil, fmt.Errorf("workload catalog schema_version must be 2, got %d", file.SchemaVersion)
	}
	if len(file.Workloads) == 0 {
		return nil, fmt.Errorf("workload catalog contains no workloads")
	}
	catalog := &Catalog{}
	names := make(map[string]bool, len(file.Workloads))
	for _, workload := range file.Workloads {
		if err := validateWorkload(workload); err != nil {
			return nil, err
		}
		if names[workload.Name] {
			return nil, fmt.Errorf("workload catalog lists %q more than once", workload.Name)
		}
		names[workload.Name] = true
		catalog.workloads = append(catalog.workloads, workload)
	}
	sort.Slice(catalog.workloads, func(i, j int) bool {
		return catalog.workloads[i].Name < catalog.workloads[j].Name
	})
	return catalog, nil
}

func validateWorkload(workload *Workload) error {
	if workload.Name == "" || workload.Version == "" {
		return fmt.Errorf("workload catalog entry must have a name and version")
	}
	switch workload.Reduction {
	case "top-k", "ordered-concat":
	default:
		return fmt.Errorf("workload %q declares unknown reduction %q", workload.Name, workload.Reduction)
	}
	if err := validateSchema(workload.Name, workload.Parameters); err != nil {
		return err
	}
	workload.parameterDefaults = schemaDefaults(workload.Parameters)
	workload.requiredColumns = map[string]bool{}
	for portName, port := range workload.Inputs {
		config, ok := port.(map[string]any)
		if !ok {
			continue
		}
		validator, _ := config["validator_configuration"].(map[string]any)
		columns, _ := validator["required_columns"].([]any)
		for _, column := range columns {
			text, ok := column.(string)
			if ok {
				workload.requiredColumns[text] = true
			}
		}
		if mediaType, ok := config["media_type"].(string); ok {
			if workload.inputMediaTypes == nil {
				workload.inputMediaTypes = map[string]string{}
			}
			workload.inputMediaTypes[portName] = mediaType
		}
	}
	for _, element := range workload.UIElements {
		if err := validateUIElement(workload, element); err != nil {
			return err
		}
	}
	return nil
}

func validateUIElement(workload *Workload, element UIElement) error {
	switch element.Widget {
	case "text", "textarea", "number", "select", "checkbox":
	default:
		return fmt.Errorf("workload %q ui element %q has unknown widget %q", workload.Name, element.Field, element.Widget)
	}
	if element.Widget == "select" && len(element.Options) == 0 {
		return fmt.Errorf("workload %q ui element %q is a select without options", workload.Name, element.Field)
	}
	properties, ok := workload.Parameters["properties"].(map[string]any)
	if !ok {
		return nil
	}
	property, declared := properties[element.Field].(map[string]any)
	if !declared {
		return fmt.Errorf("workload %q ui element %q does not name a declared parameter", workload.Name, element.Field)
	}
	if schemaType(property) == "boolean" && element.Widget != "checkbox" {
		return fmt.Errorf("workload %q ui element %q must use the checkbox widget for a boolean parameter", workload.Name, element.Field)
	}
	return nil
}

// Enabled returns the enabled workloads, sorted by name.
func (c *Catalog) Enabled() []*Workload {
	result := make([]*Workload, 0, len(c.workloads))
	for _, workload := range c.workloads {
		if workload.Enabled {
			result = append(result, workload)
		}
	}
	return result
}

// ByName returns the workload with the given name, or nil.
func (c *Catalog) ByName(name string) *Workload {
	for _, workload := range c.workloads {
		if workload.Name == name {
			return workload
		}
	}
	return nil
}

// ValidateParameters checks job parameters against the workload schema. It
// enforces the strict subset of JSON Schema used by the SDK manifests: object
// shape, types, required, enum, numeric bounds, string lengths, and oneOf.
func (c *Catalog) ValidateParameters(name string, parameters map[string]any) error {
	workload := c.ByName(name)
	if workload == nil {
		return fmt.Errorf("unknown workload %q", name)
	}
	if !workload.Enabled {
		return fmt.Errorf("workload %q is not enabled", name)
	}
	return validateParameters(name, workload.Parameters, parameters)
}

// UploadReady reports whether the workload can be driven from a single
// uploaded dataset file. Workloads that need planner-produced inputs (such as
// the graph block-pair shards) declare upload_ready=false.
func (c *Catalog) UploadReady(name string) bool {
	workload := c.ByName(name)
	if workload == nil {
		return false
	}
	return workload.UploadReady
}

// RequiredColumns reports every column the workload's input port requires.
func (c *Catalog) RequiredColumns(name string) map[string]bool {
	workload := c.ByName(name)
	if workload == nil {
		return nil
	}
	return workload.requiredColumns
}

// InputMediaType returns the declared media type of the named input port.
func (c *Catalog) InputMediaType(name, port string) string {
	workload := c.ByName(name)
	if workload == nil {
		return ""
	}
	return workload.inputMediaTypes[port]
}

// InputPortNames returns the sorted input port names of the workload.
func (c *Catalog) InputPortNames(name string) []string {
	workload := c.ByName(name)
	if workload == nil {
		return nil
	}
	names := make([]string, 0, len(workload.Inputs))
	for port := range workload.Inputs {
		names = append(names, port)
	}
	sort.Strings(names)
	return names
}

// Reduction returns the reduction mode for the workload, or "" if unknown.
func (c *Catalog) Reduction(name string) string {
	workload := c.ByName(name)
	if workload == nil {
		return ""
	}
	return workload.Reduction
}

// ParameterDefaults returns the schema-declared defaults for the workload.
func (c *Catalog) ParameterDefaults(name string) map[string]any {
	workload := c.ByName(name)
	if workload == nil {
		return nil
	}
	return workload.parameterDefaults
}

// ParameterSchema returns the schema property for a workload parameter, and
// whether the parameter exists.
func (w *Workload) PropertySchema(field string) (map[string]any, bool) {
	properties, ok := w.Parameters["properties"].(map[string]any)
	if !ok {
		return nil, false
	}
	property, ok := properties[field].(map[string]any)
	return property, ok
}
